version: "3.7"

services:
  ms:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./docker-data:/dev-docker-data
      - ./configs:/configs
      - ./mail:/var/mail
    env_file:
      - ms.env
    ports:
      - "25:25"
      - "143:143"
    container_name: ms
