version: "3.7"

services:
  ms:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./docker-data:/dev-docker-data
      - ./configs:/configs
      - ./mail:/var/mail
    ports:
      - "25:25"       # smtp
      - "110:110"     # pop3
      - "143:143"     # imap
    container_name: ms
