version: "3.7"

services:
  ms:
    image: ${MAILSERVER_IMAGE}
    volumes:
      - ./configs:/configs
      - ./${MAILSERVER_MAILS_PATH}:/var/mail
    ports:
      - "25:25"       # smtp
      - "465:465"     # smtps
      - "110:110"     # pop3
      - "143:143"     # imap
      - "993:993"     # imaps
      - "995:995"     # pop3s
    container_name: ms
